#backend:
#  name: github
#  repo: jpuptagrafft/week_8-10
#  branch: master # Branch to update (optional; defaults to master)
#  media_folder: "images"
backend:
  name: github
  repo: jpuptagrafft/week_8-10
media_folder: 'images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }